### PR TITLE
Make sure we fetch as an URL if we install using a github URL

### LINKED ISSUE #94: git deps get failing when fetching a Github URL
**Describe the bug**

`git deps get` fails when fetching a Github URL

**To Reproduce**

1. Run `clio deps add https://github.com/clio-lang/rethinkdb/archive/v2.3.3.zip`
2. See error
```
{
  _: [ 'deps', 'add' ],
  '$0': '/usr/local/bin/clio',
  url: 'https://github.com/clio-lang/rethinkdb/archive/v2.3.3.zip'
}
Downloading https://github.com/clio-lang/rethinkdb/archive/v2.3.3.zip...
Added https://github.com/clio-lang/rethinkdb/archive/v2.3.3.zip to the dependencies list
FetchError: request to https://https//github.com/clio-lang/rethinkdb/archive/v2.3.3.zip/archive/master.zip failed, reason: getaddrinfo ENOTFOUND
```

3. No directory `rethinkdb-2.3.3` in `clio_env`.

**Expected behavior**

We should find a directory `rethinkdb-2.3.3` in `clio_env` and no error.

**Versions (please complete the following information):**

 - OS: Mac OS X 10.15.2
 - Clio: 0.1.6
 - Node: v13.5.0
 - NPM: 6.13.4
 
**Possible solutions**

 - malformed URL

### PR DESCRIPTION
**Pull request by mindrones**
Fixes #94

### CODE REVIEW

File: internals/deps/index.js [hunk 1]
```diff
@@ -36,7 +36,11 @@ function getDependencies() {
     return;
   }
 
-  return Promise.all(packageConfig.getPackageDependencies().map(dep => get({ source: dep.name })));
+  return Promise.all(
```
Comment (garritfra) [inline internals/deps/index.js]: We use prettier as our code formatter. Just ran it for this snippet, its supposed to be a one liner :) You can quick-fix it with the `lint:fix` script

Comment (garritfra) [reply internals/deps/index.js]: I don't know why the push checks didn't detect that. I'll investigate that.
